<?php
/**
 * Zkilleman_Lookbook
 *
 * Copyright (C) 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 *
 * This file is part of Zkilleman_Lookbook.
 *
 * Zkilleman_Lookbook is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zkilleman_Lookbook is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zkilleman_Lookbook. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category Zkilleman
 * @package Zkilleman_Lookbook
 * @author Henrik Hedelund <henke.hedelund@gmail.com>
 * @copyright 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 * @license http://www.gnu.org/licenses/gpl.html GNU GPL
 * @link https://github.com/henkelund/magento-zkilleman-lookbook
 */
?>
<?php $element = $this->getElement(); ?>
<div id="lookbookImageWrapper">
    <img id="lookbookImage" src="<?php echo $element->getUrl(); ?>" />
</div>
<ul id="lookbookTagList"></ul>
<input type="hidden" id="lookbookImageFocusX" name="focus_x" value="<?php echo $element->getFocusX(); ?>" />
<input type="hidden" id="lookbookImageFocusY" name="focus_y" value="<?php echo $element->getFocusY(); ?>" />
<script type="text/javascript">
//<![CDATA[
    $('lookbookImage').observe('load', function() {
        new LookbookCrosshair({
            imageId:  'lookbookImage',
            focusXId: 'lookbookImageFocusX',
            focusYId: 'lookbookImageFocusY',
            title:    '<?php echo $this->__('Double click to center focus'); ?>'
        });
        new LookbookTagInput({
            tagListId: 'lookbookTagList',
            imageId:   'lookbookImage',
            fieldName: '<?php echo $element->getName(); ?>',
            suggestionUrl: '<?php echo $this->getUrl('*/adminhtml_image_tag/suggestion'); ?>'
        });
        <?php if ($element->getTags()): foreach ($element->getTags() as $tag): ?>
            new LookbookTag(
                <?php echo $tag->toJson(); ?>,
                {
                    tagListId: 'lookbookTagList',
                    imageId:   'lookbookImage',
                    fieldName: '<?php echo $element->getName(); ?>'
                }
            );
        <?php endforeach; endif; ?>
    });
//]]>
</script>