<?php
/**
 * Zkilleman_Lookbook
 *
 * Copyright (C) 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 *
 * This file is part of Zkilleman_Lookbook.
 *
 * Zkilleman_Lookbook is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zkilleman_Lookbook is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zkilleman_Lookbook. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category Zkilleman
 * @package Zkilleman_Lookbook
 * @author Henrik Hedelund <henke.hedelund@gmail.com>
 * @copyright 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 * @license http://www.gnu.org/licenses/gpl.html GNU GPL
 * @link https://github.com/henkelund/magento-zkilleman-lookbook
 */
?>
<?php 
    $product = $this->getProduct();
    $title = $product ? $product->getName() : $this->__('No product selected');
    $info  = $product ? 
                Mage::helper('core/string')->substr($product->getDescription(), 0, 30) : 
                $this->__('Please enter search term below');
    $st = $this->__('Type to search..'); // search text
?>
<div class="image-tag-product">
    <input 
        id="<?php echo $this->getFieldId(); ?>"
        name="<?php echo $this->getFieldName(); ?>"
        type="hidden"
        value="<?php echo $this->getValue(); ?>" />
    <div class="product-info" id="<?php echo $this->getFieldId(); ?>Name">
        <strong><?php echo $title; ?></strong>
        <br />
        <span class="informal"><?php echo $info; ?></span>
    </div>
    <input 
        id="<?php echo $this->getFieldId(); ?>Input"
        type="text"
        class="input-text"
        value="<?php echo $st; ?>"
        onfocus="if (this.value == '<?php echo $st; ?>') this.value='';"
        onblur="this.value='<?php echo $st; ?>';"
        />
    <div class="autocomplete" id="<?php echo $this->getFieldId(); ?>AC"></div>
</div>
<script type="text/javascript">
//<![CDATA[
    new Ajax.Autocompleter(
        '<?php echo $this->getFieldId(); ?>Input',
        '<?php echo $this->getFieldId(); ?>AC',
        '<?php echo $this->getUrl('*/adminhtml_image_tag_product/autocomplete'); ?>',
        {
            paramName: 'q',
            updateElement: function(li) {
                $('<?php echo $this->getFieldId(); ?>').value = li.getAttribute('rel');
                $('<?php echo $this->getFieldId(); ?>Name').innerHTML = li.innerHTML;
                var input = $('<?php echo $this->getFieldId(); ?>Input');
                input.value = '';
                input.blur();
            }
        }
    );
//]]>
</script>