<?php
/**
 * Zkilleman_Lookbook
 *
 * Copyright (C) 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 *
 * This file is part of Zkilleman_Lookbook.
 *
 * Zkilleman_Lookbook is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zkilleman_Lookbook is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zkilleman_Lookbook. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category Zkilleman
 * @package Zkilleman_Lookbook
 * @author Henrik Hedelund <henke.hedelund@gmail.com>
 * @copyright 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 * @license http://www.gnu.org/licenses/gpl.html GNU GPL
 * @link https://github.com/henkelund/magento-zkilleman-lookbook
 */
?>
<?php
    $helper    = Mage::helper('lookbook');
    $canFilter = Mage::getSingleton('lookbook/config')->isRequestTagsAllowed();
    $imageHtml = $this->getImageHtml();
?>
<div id="<?php echo $this->getHtmlId(); ?>" class="overlay-bar-image">
    <?php echo $imageHtml; ?>
    <div class="bar">
        <?php if ($this->hasTags()): ?>
        <div class="tags">
            <label><?php echo $this->__('Tags:'); ?></label>
            <?php $tagHtml = array(); ?>
            <?php foreach ($this->getTags() as $tag): ob_start(); ?>
            <span class="tag"><!--
                --><?php if ($canFilter): ?><a href="<?php echo $helper->getTagUrl($tag->getName()); ?>"><?php endif; ?><!--
                    --><?php echo $tag->getName(); ?><!--
                --><?php if ($canFilter): ?></a><?php endif; ?><!--
            --></span>
            <?php $tagHtml[] = trim(ob_get_clean()); endforeach; ?>
            <?php echo implode(', ', $tagHtml); ?>
        </div>
        <?php endif; ?>
        <span class="title"><?php echo $this->getTitle(); ?></span>
        <p class="caption"><?php echo $this->getCaption(); ?></p>
    </div>
    <?php foreach ($this->getVisibleTags() as $tag): ?>
    <div class="positioned-tag <?php echo $tag->getType(); ?>"
            data-id="<?php echo $tag->getId(); ?>"
            data-type="<?php echo $tag->getType(); ?>"
            data-x="<?php echo $tag->getRelX(); ?>"
            data-y="<?php echo $tag->getRelY(); ?>">
        <?php if ($canFilter): ?>
        <a href="<?php echo $helper->getTagUrl($tag); ?>"><?php echo $tag->getName(); ?></a>
        <?php else: ?>
        <?php echo $tag->getName(); ?>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
</div>
<script type="text/javascript">
//<![CDATA
    new LookbookOverlayBarImage('<?php echo $this->getHtmlId(); ?>');
//]]>
</script>
