<?php
/**
 * Zkilleman_Lookbook
 *
 * Copyright (C) 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 *
 * This file is part of Zkilleman_Lookbook.
 *
 * Zkilleman_Lookbook is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zkilleman_Lookbook is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zkilleman_Lookbook. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category Zkilleman
 * @package Zkilleman_Lookbook
 * @author Henrik Hedelund <henke.hedelund@gmail.com>
 * @copyright 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 * @license http://www.gnu.org/licenses/gpl.html GNU GPL
 * @link https://github.com/henkelund/magento-zkilleman-lookbook
 */
?>
<?php 
    $images  = $this->getImageCollection();
    $width   = $this->getWidth();
    $cols    = 4;
    $padding = 5;
    $wall    = Mage::getModel('lookbook/masonry_brick', array('width' => $width));

    foreach ($images as $image) {
        $imageWidth = round($width/$cols) - 2*$padding;
        $brick = Mage::getModel('lookbook/masonry_brick', array(
            'width'       => $imageWidth + 2*$padding,
            'height'      => $imageWidth*$image->getRatio() + 2*$padding,
            'image'       => $image,
            'image_width' => $imageWidth,
            'padding'     => $padding
            ));
        $wall->append($brick);
    }
?>
<div id="<?php echo $this->getHtmlId(); ?>"
     class="masonry-canvas"
     style="position: relative; <?php echo (string) $wall; ?>">
<?php foreach ($wall->getChildren() as $brick): ?>
    <div class="brick"
         style="position: absolute; padding: <?php echo $padding; ?>px; <?php echo (string) $brick; ?>"
         data-hrb="<?php echo $brick->getHighestRowBottom(); ?>">
        <?php echo $brick->getImage()->getHtml($brick->getImageWidth()); ?>
    </div>
<?php endforeach; ?>
</div>
