<?php
/**
 * Zkilleman_Lookbook
 *
 * Copyright (C) 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 *
 * This file is part of Zkilleman_Lookbook.
 *
 * Zkilleman_Lookbook is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zkilleman_Lookbook is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zkilleman_Lookbook. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category Zkilleman
 * @package Zkilleman_Lookbook
 * @author Henrik Hedelund <henke.hedelund@gmail.com>
 * @copyright 2012 Henrik Hedelund (henke.hedelund@gmail.com)
 * @license http://www.gnu.org/licenses/gpl.html GNU GPL
 * @link https://github.com/henkelund/magento-zkilleman-lookbook
 */
?>
<?php
    $items = $this->getImageBlocks();
    // The item list is padded with fake items at the
    // beginning and the end to achive a seamless loop.
    // If the item width is much less than the slideshow
    // width the number of fakes has to be increased.
    // So, @todo Don't hard code $numFakes
    $numFakes = 2;
    if (count($items) > 0) {
        for ($i = 0; $i < $numFakes; ++$i) {
            $first = $items[$i*2];
            $last = $items[count($items) - (($i*2) + 1)];
            array_unshift($items, $last);
            array_push($items, $first);
        }
    }
?>
<div class="slideshow-wrapper">
    <ul id="<?php echo $this->getHtmlId(); ?>" class="slideshow"><!--
    <?php $i = 0; foreach ($items as $item): ?>
        <?php
            $isFake = $i < $numFakes || $i > (count($items) - $numFakes) - 1;
            $itemHtml;
            if ($isFake) {
                $itemName = $item->getHtmlId();
                $item->setHtmlId($itemName . '_fake');
                $item->setNoImageHtmlCache(true);
                $itemHtml = $item->toHtml();
                $item->setNoImageHtmlCache(false);
                $item->setHtmlId($itemName);
            } else {
                $itemHtml = $item->toHtml();
            }
        ?>
     --><li class="item<?php if ($isFake): ?> fake<?php endif; ?>">
            <?php echo $itemHtml; ?>
        </li><!--
    <?php ++$i; endforeach; ?>
 --></ul>
    <button class="previous" title="<?php echo $this->__('Previous'); ?>">&laquo;</button>
    <button class="next" title="<?php echo $this->__('Next'); ?>">&raquo;</button>
</div>
<script type="text/javascript">
    
    new LookbookSlideshow(
            '<?php echo $this->getHtmlId(); ?>',
            {
                direction: '<?php echo $this->getDirection(); ?>',
                interval:  <?php echo $this->getInterval(); ?>
            });
    
</script>
